import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { useAuth } from './AuthContext';
import { getCheckIns, getGoals, getTasks, getUserProfile, removeGoal, saveCheckIn, saveGoal, saveTask, saveUserProfile, updateGoal } from '../lib/firestore';
import type { CheckIn, DailyTask, Goal, GoalCategory, TaskStatus, UserProfile } from '../types';
const empty: UserProfile = { uid: '', name: '', email: '', categories: [], mission: '', commitment: 30, onboardingCompleted: false, startDate: null, createdAt: '', updatedAt: '' };
const colors: Record<GoalCategory, string> = { Mind: 'bg-violet-100 text-violet-700', Fitness: 'bg-emerald-100 text-emerald-700', Health: 'bg-cyan-100 text-cyan-700', Career: 'bg-blue-100 text-blue-700', Education: 'bg-indigo-100 text-indigo-700', Passion: 'bg-fuchsia-100 text-fuchsia-700', Finance: 'bg-amber-100 text-amber-700', Discipline: 'bg-stone-200 text-stone-700', Reading: 'bg-orange-100 text-orange-700', Other: 'bg-slate-100 text-slate-700' };
interface StateValue { profile: UserProfile; goals: Goal[]; tasks: DailyTask[]; checkIns: CheckIn[]; loading: boolean; error: string; completeOnboarding(data: Omit<UserProfile, 'uid'|'email'|'createdAt'|'updatedAt'|'onboardingCompleted'|'startDate'> & { name: string; initialActivities: Array<Omit<Goal, 'id'|'userId'|'active'|'color'|'createdAt'>> }): Promise<void>; addGoal(data: Omit<Goal, 'id'|'userId'|'active'|'color'|'createdAt'>): Promise<void>; editGoal(goal: Goal): Promise<void>; deleteGoal(id: string): Promise<void>; toggleTask(task: DailyTask): Promise<void>; saveCheckIn(item: CheckIn): Promise<void>; }
const Context = createContext<StateValue | null>(null); const today = () => new Date().toISOString().slice(0, 10);
export function AppStateProvider({ children }: { children: ReactNode }) { const { user } = useAuth(); const [profile, setProfile] = useState(empty); const [goals, setGoals] = useState<Goal[]>([]); const [tasks, setTasks] = useState<DailyTask[]>([]); const [checkIns, setCheckIns] = useState<CheckIn[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); useEffect(() => { let cancelled = false; if (!user) { setProfile(empty); setGoals([]); setTasks([]); setCheckIns([]); return; } setLoading(true); Promise.all([getUserProfile(user.uid), getGoals(user.uid), getTasks(user.uid), getCheckIns(user.uid)]).then(([savedProfile, savedGoals, savedTasks, savedCheckIns]) => { if (!cancelled) { setProfile(savedProfile ?? { ...empty, uid: user.uid, email: user.email ?? '', name: user.displayName ?? '', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); setGoals(savedGoals); setTasks(savedTasks); setCheckIns(savedCheckIns); } }).catch((caught) => !cancelled && setError(caught instanceof Error ? caught.message : 'Could not load your journey.')).finally(() => !cancelled && setLoading(false)); return () => { cancelled = true; }; }, [user]);
const value = useMemo<StateValue>(() => ({ profile, goals, tasks, checkIns, loading, error, completeOnboarding: async (data) => { if (!user) throw new Error('Please sign in first.'); const now = new Date().toISOString(); const next: UserProfile = { uid: user.uid, email: user.email ?? '', name: data.name, categories: data.categories, mission: data.mission, commitment: data.commitment, onboardingCompleted: true, startDate: profile.startDate ?? today(), createdAt: profile.createdAt || now, updatedAt: now }; await saveUserProfile(next); for (const activity of data.initialActivities) await saveGoal(user.uid, { ...activity, id: `goal-${crypto.randomUUID()}`, userId: user.uid, active: true, color: colors[activity.category], createdAt: now }, next.startDate!); setProfile(next); setGoals(await getGoals(user.uid)); setTasks(await getTasks(user.uid)); }, addGoal: async (data) => { if (!user) throw new Error('Please sign in first.'); const goal: Goal = { ...data, id: `goal-${crypto.randomUUID()}`, userId: user.uid, active: true, color: colors[data.category], createdAt: new Date().toISOString() }; await saveGoal(user.uid, goal, profile.startDate ?? today()); setGoals((items) => [...items, goal]); setTasks(await getTasks(user.uid)); }, editGoal: async (goal) => { if (!user) throw new Error('Please sign in first.'); await updateGoal(user.uid, goal); setGoals((items) => items.map((item) => item.id === goal.id ? goal : item)); }, deleteGoal: async (id) => { if (!user) throw new Error('Please sign in first.'); await removeGoal(user.uid, id); setGoals((items) => items.filter((item) => item.id !== id)); setTasks((items) => items.filter((item) => item.goalId !== id)); }, toggleTask: async (task) => { if (!user) throw new Error('Please sign in first.'); const next: DailyTask = { ...task, status: task.status === 'completed' ? 'not-completed' : 'completed', completedValue: task.status === 'completed' ? 0 : task.targetValue, completedAt: task.status === 'completed' ? undefined : new Date().toISOString() }; await saveTask(user.uid, next); setTasks((items) => items.map((item) => item.id === task.id ? next : item)); }, saveCheckIn: async (item) => { if (!user) throw new Error('Please sign in first.'); await saveCheckIn(user.uid, item); setCheckIns((items) => [...items.filter((entry) => entry.date !== item.date), item]); } }), [profile, goals, tasks, checkIns, loading, error, user]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export function useAppState() { const value = useContext(Context); if (!value) throw new Error('useAppState must be used inside AppStateProvider'); return value; }
